### ISSUE TITLE
Report on issues

### ISSUE THREAD

**Issue by arthur-shaw** [arthur-shaw/susoreview#6]
# Objective 🎯

Provide a standard report on issues

In more words:

Every tool that checks incoming data compiles issues, but no tool currently generates a report that summarizes issues. This proposal will develop a report on issues–on the top issues, on issues by team, and on selected issues over time. This report would be automatically generated each time data checking tools, such as auto-reject are run.

# User stories 📇

## Scope

Geographic:

- Overall
- For group of teams
- For a single team

Issues:

- Created by susoreview
- Created by SuSo
- Created by external high-frequency checks

## Content

- Top issues
- Issues by team
- Issues over time

# Tasks ⚙️

## Scoping 🔭 

- [ ] Identify components
- [ ] Develop prototypes
- [ ] Get feedback on prototypes
- [ ] See if/how SuSo issues could be integrated
- [ ] See if/how high-frequency check issues could be integrated
- [ ] Think about which make sense for each level (e.g., HQ, supervisor, interviewer)

## Development 👨‍💻 

- [ ] Develop template
- [ ] Consider building wizard for selecting components
- [ ] Consider adding as template in susoreview package

## Documentation ✍️ 

- [ ] Create section in reference index page
- [ ] Write vignette on working with calendar events
